[theme]
primaryColor="#1E3A8A"         # Royal Dark Blue (buttons, highlights)
backgroundColor="#F8FAFC"      # Very light gray (clean medical background)
secondaryBackgroundColor="#E2E8F0"  # Light neutral gray for cards/containers
textColor="#111827"            # Deep black text for readability
font="sans serif"              # Clean modern font

[server]
headless = true
